services:
  ecommerce-pos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-pos-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - ecommerce-network
    volumes:
      # Opcional: Para persistir logs o datos si es necesario
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ecommerce-network:
    driver: bridge

volumes:
  logs:
    driver: local
