"""initial_schema

Revision ID: e23e20872fc1
Revises: 
Create Date: 2026-01-28 14:19:43.868738-03:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e23e20872fc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration changes to upgrade the database schema.
    
    This function is executed when running 'alembic upgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_branch_ecommerce_config_branch_id', table_name='branch_ecommerce_config')
    op.drop_table('branch_ecommerce_config')
    op.drop_index('idx_branch_whatsapp_config_branch_id', table_name='branch_whatsapp_config')
    op.drop_table('branch_whatsapp_config')
    op.drop_index('idx_branch_payment_methods_branch_id', table_name='branch_payment_methods')
    op.drop_index('idx_branch_payment_methods_is_active', table_name='branch_payment_methods', postgresql_where='(is_active = true)')
    op.drop_index('idx_branch_payment_methods_payment_method_id', table_name='branch_payment_methods')
    op.drop_index('idx_branch_tax_rates_branch_id', table_name='branch_tax_rates')
    op.drop_index('idx_branch_tax_rates_is_default', table_name='branch_tax_rates', postgresql_where='(is_default = true)')
    op.drop_index('idx_branch_tax_rates_tax_rate_id', table_name='branch_tax_rates')
    op.drop_index('idx_config_change_log_changed_at', table_name='config_change_log')
    op.drop_index('idx_config_change_log_record_id', table_name='config_change_log')
    op.drop_index('idx_config_change_log_table_name', table_name='config_change_log')
    op.drop_index('idx_config_change_log_table_record', table_name='config_change_log')
    op.drop_index('idx_config_change_log_user_id', table_name='config_change_log')
    op.alter_column('custom_installments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique identifier for the installment plan',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('custom_installments', 'card_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Card type: bancarizadas or no_bancarizadas',
               existing_nullable=False)
    op.alter_column('custom_installments', 'installments',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of installments (1-60)',
               existing_nullable=False)
    op.alter_column('custom_installments', 'surcharge_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Surcharge percentage (0.00-100.00)',
               existing_nullable=False)
    op.alter_column('custom_installments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this plan is currently active',
               existing_nullable=False)
    op.alter_column('custom_installments', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Description of the installment plan',
               existing_nullable=False)
    op.alter_column('custom_installments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was created',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_installments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the record was last updated',
               existing_nullable=True)
    op.drop_index('idx_custom_installments_active', table_name='custom_installments')
    op.drop_index('idx_custom_installments_card_type', table_name='custom_installments')
    op.drop_index('idx_custom_installments_card_type_active', table_name='custom_installments')
    op.drop_index('idx_custom_installments_payment_method_id', table_name='custom_installments')
    op.drop_constraint('uk_card_type_installments', 'custom_installments', type_='unique')
    op.drop_constraint('fk_custom_installments_payment_method', 'custom_installments', type_='foreignkey')
    op.drop_table_comment(
        'custom_installments',
        existing_comment='Custom installment plans for credit cards with personalized surcharges',
        schema=None
    )
    op.drop_column('custom_installments', 'payment_method_id')
    op.drop_constraint('fk_ecommerce_config_updated_by', 'ecommerce_config', type_='foreignkey')
    op.drop_constraint('fk_ecommerce_config_created_by', 'ecommerce_config', type_='foreignkey')
    op.drop_column('ecommerce_config', 'updated_by_user_id')
    op.drop_column('ecommerce_config', 'created_by_user_id')
    op.drop_index('idx_payment_config_created_by', table_name='payment_config')
    op.drop_index('idx_payment_config_payment_method_id', table_name='payment_config')
    op.drop_constraint('fk_payment_config_payment_method', 'payment_config', type_='foreignkey')
    op.drop_constraint('payment_config_updated_by_user_id_fkey', 'payment_config', type_='foreignkey')
    op.drop_constraint('payment_config_created_by_user_id_fkey', 'payment_config', type_='foreignkey')
    op.drop_column('payment_config', 'updated_by_user_id')
    op.drop_column('payment_config', 'created_by_user_id')
    op.drop_column('payment_config', 'payment_method_id')
    op.alter_column('payment_methods', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Unique code (e.g., 'CASH', 'CARD', 'TRANSFER')",
               existing_comment="Unique code (e.g., 'CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'TRANSFER')",
               existing_nullable=False)
    op.drop_index('idx_sales_payment_method_id', table_name='sales')
    op.drop_index('idx_sales_referral_banner_id', table_name='sales')
    op.drop_index('idx_sales_tax_rate_id', table_name='sales')
    op.drop_constraint('fk_sales_referral_banner', 'sales', type_='foreignkey')
    op.drop_column('sales', 'referral_banner_id')
    op.drop_index('idx_security_audit_log_created_at', table_name='security_audit_log')
    op.drop_index('idx_security_audit_log_event_type', table_name='security_audit_log')
    op.drop_index('idx_security_audit_log_failed_logins', table_name='security_audit_log', postgresql_where="(((event_type)::text = 'LOGIN'::text) AND ((success)::text = 'FAILED'::text))")
    op.drop_index('idx_security_audit_log_ip_address', table_name='security_audit_log')
    op.drop_index('idx_security_audit_log_user_id', table_name='security_audit_log')
    op.drop_index('idx_security_audit_log_username', table_name='security_audit_log')
    op.drop_constraint('fk_social_media_config_created_by', 'social_media_config', type_='foreignkey')
    op.drop_constraint('fk_social_media_config_updated_by', 'social_media_config', type_='foreignkey')
    op.drop_column('social_media_config', 'updated_by_user_id')
    op.drop_column('social_media_config', 'created_by_user_id')
    op.drop_constraint('fk_store_banners_updated_by', 'store_banners', type_='foreignkey')
    op.drop_constraint('fk_store_banners_created_by', 'store_banners', type_='foreignkey')
    op.drop_column('store_banners', 'updated_by_user_id')
    op.drop_column('store_banners', 'created_by_user_id')
    op.drop_constraint('fk_system_config_tax_rate', 'system_config', type_='foreignkey')
    op.drop_constraint('fk_whatsapp_config_created_by', 'whatsapp_config', type_='foreignkey')
    op.drop_constraint('fk_whatsapp_config_updated_by', 'whatsapp_config', type_='foreignkey')
    op.drop_column('whatsapp_config', 'updated_by_user_id')
    op.drop_column('whatsapp_config', 'created_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert migration changes to downgrade the database schema.
    
    This function is executed when running 'alembic downgrade'.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_config', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('whatsapp_config', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_whatsapp_config_updated_by', 'whatsapp_config', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_whatsapp_config_created_by', 'whatsapp_config', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_system_config_tax_rate', 'system_config', 'tax_rates', ['default_tax_rate'], ['id'], ondelete='RESTRICT')
    op.add_column('store_banners', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('store_banners', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_store_banners_created_by', 'store_banners', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_store_banners_updated_by', 'store_banners', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('social_media_config', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('social_media_config', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_social_media_config_updated_by', 'social_media_config', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_social_media_config_created_by', 'social_media_config', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_security_audit_log_username', 'security_audit_log', ['username'], unique=False)
    op.create_index('idx_security_audit_log_user_id', 'security_audit_log', ['user_id'], unique=False)
    op.create_index('idx_security_audit_log_ip_address', 'security_audit_log', ['ip_address'], unique=False)
    op.create_index('idx_security_audit_log_failed_logins', 'security_audit_log', ['event_type', 'success', 'created_at'], unique=False, postgresql_where="(((event_type)::text = 'LOGIN'::text) AND ((success)::text = 'FAILED'::text))")
    op.create_index('idx_security_audit_log_event_type', 'security_audit_log', ['event_type'], unique=False)
    op.create_index('idx_security_audit_log_created_at', 'security_audit_log', [sa.text('created_at DESC')], unique=False)
    op.add_column('sales', sa.Column('referral_banner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_sales_referral_banner', 'sales', 'store_banners', ['referral_banner_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_sales_tax_rate_id', 'sales', ['tax_rate_id'], unique=False)
    op.create_index('idx_sales_referral_banner_id', 'sales', ['referral_banner_id'], unique=False)
    op.create_index('idx_sales_payment_method_id', 'sales', ['payment_method_id'], unique=False)
    op.alter_column('payment_methods', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment="Unique code (e.g., 'CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'TRANSFER')",
               existing_comment="Unique code (e.g., 'CASH', 'CARD', 'TRANSFER')",
               existing_nullable=False)
    op.add_column('payment_config', sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payment_config', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payment_config', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_config_created_by_user_id_fkey', 'payment_config', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payment_config_updated_by_user_id_fkey', 'payment_config', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_payment_config_payment_method', 'payment_config', 'payment_methods', ['payment_method_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_payment_config_payment_method_id', 'payment_config', ['payment_method_id'], unique=False)
    op.create_index('idx_payment_config_created_by', 'payment_config', ['created_by_user_id'], unique=False)
    op.add_column('ecommerce_config', sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ecommerce_config', sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_ecommerce_config_created_by', 'ecommerce_config', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ecommerce_config_updated_by', 'ecommerce_config', 'users', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('custom_installments', sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'custom_installments',
        'Custom installment plans for credit cards with personalized surcharges',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('fk_custom_installments_payment_method', 'custom_installments', 'payment_methods', ['payment_method_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uk_card_type_installments', 'custom_installments', ['card_type', 'installments'])
    op.create_index('idx_custom_installments_payment_method_id', 'custom_installments', ['payment_method_id'], unique=False)
    op.create_index('idx_custom_installments_card_type_active', 'custom_installments', ['card_type', 'is_active'], unique=False)
    op.create_index('idx_custom_installments_card_type', 'custom_installments', ['card_type'], unique=False)
    op.create_index('idx_custom_installments_active', 'custom_installments', ['is_active'], unique=False)
    op.alter_column('custom_installments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was last updated',
               existing_nullable=True)
    op.alter_column('custom_installments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the record was created',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('custom_installments', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment='Description of the installment plan',
               existing_nullable=False)
    op.alter_column('custom_installments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this plan is currently active',
               existing_nullable=False)
    op.alter_column('custom_installments', 'surcharge_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Surcharge percentage (0.00-100.00)',
               existing_nullable=False)
    op.alter_column('custom_installments', 'installments',
               existing_type=sa.INTEGER(),
               comment='Number of installments (1-60)',
               existing_nullable=False)
    op.alter_column('custom_installments', 'card_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Card type: bancarizadas or no_bancarizadas',
               existing_nullable=False)
    op.alter_column('custom_installments', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique identifier for the installment plan',
               existing_nullable=False,
               autoincrement=True)
    op.create_index('idx_config_change_log_user_id', 'config_change_log', ['changed_by_user_id'], unique=False)
    op.create_index('idx_config_change_log_table_record', 'config_change_log', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_config_change_log_table_name', 'config_change_log', ['table_name'], unique=False)
    op.create_index('idx_config_change_log_record_id', 'config_change_log', ['record_id'], unique=False)
    op.create_index('idx_config_change_log_changed_at', 'config_change_log', [sa.text('changed_at DESC')], unique=False)
    op.create_index('idx_branch_tax_rates_tax_rate_id', 'branch_tax_rates', ['tax_rate_id'], unique=False)
    op.create_index('idx_branch_tax_rates_is_default', 'branch_tax_rates', ['branch_id', 'is_default'], unique=False, postgresql_where='(is_default = true)')
    op.create_index('idx_branch_tax_rates_branch_id', 'branch_tax_rates', ['branch_id'], unique=False)
    op.create_index('idx_branch_payment_methods_payment_method_id', 'branch_payment_methods', ['payment_method_id'], unique=False)
    op.create_index('idx_branch_payment_methods_is_active', 'branch_payment_methods', ['branch_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_branch_payment_methods_branch_id', 'branch_payment_methods', ['branch_id'], unique=False)
    op.create_table('branch_whatsapp_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('custom_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('custom_business_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('custom_welcome_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_branch_whatsapp_config_branch', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='branch_whatsapp_config_pkey'),
    sa.UniqueConstraint('branch_id', name='uq_branch_whatsapp_config')
    )
    op.create_index('idx_branch_whatsapp_config_branch_id', 'branch_whatsapp_config', ['branch_id'], unique=False)
    op.create_table('branch_ecommerce_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('custom_store_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('custom_contact_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('custom_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_branch_ecommerce_config_branch', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='branch_ecommerce_config_pkey'),
    sa.UniqueConstraint('branch_id', name='uq_branch_ecommerce_config')
    )
    op.create_index('idx_branch_ecommerce_config_branch_id', 'branch_ecommerce_config', ['branch_id'], unique=False)
    # ### end Alembic commands ###
